### ISSUE TITLE
Reference to internal system

### ISSUE THREAD

**Issue by akwekprogress** [marklogic/marklogic-ai-examples#23]
https://github.com/marklogic/marklogic-ai-examples/blame/791b570096306441e8f9440601fccd0ff2a3ec5c/setup/docker-compose-12.yml#L6

There is a reference to bedford.progress.com which generates the following error. 

Error response from daemon: Get "https://ml-docker-db-dev-tierpoint.bed-artifactory.bedford.progress.com/v2/": dial tcp: lookup ml-docker-db-dev-tierpoint.bed-artifactory.bedford.progress.com on [127.0.0.53:53](https://url.us.m.mimecastprotect.com/s/0FfmCkRgEgS9M90PI2f9FGeziN?domain=127.0.0.53) no such host"

As such, public users are not able to pull the image.

**Comment by rjrudin** [comment]
Hi @akwekprogress - that's intentional, per the setup instructions at https://marklogic.github.io/marklogic-ai-examples/setup.html . If you are a Progress employee, you can access an image of MarkLogic 12 from Artifactory while on the Progress VPN. Otherwise, you'll need to contact Progress MarkLogic via https://www.progress.com/marklogic to request access to MarkLogic 12 until it is generally available.
